CREATE TABLE ProductionOperators (
    OperatorId INT IDENTITY(1,1) PRIMARY KEY,
    EmployeeNumber INT NOT NULL UNIQUE,
    NameOperator VARCHAR(50),
    LastnameOperator VARCHAR(100),
    AreaId INT,
    Operation VARCHAR(100),
    Goal INT,
    Active BIT DEFAULT 1,

    CONSTRAINT FK_ProductionOperators_Areas
        FOREIGN KEY (AreaId) REFERENCES Areas(AreaID)
);
CREATE TABLE ProductionOperatorsScans (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    OperatorId INT NOT NULL,
    Code VARCHAR(50),
    ScannedAt DATETIME DEFAULT GETDATE(),

)
--Índices recomendados (importante para rendimiento)

-- Buscar rápido por número de empleado
CREATE INDEX IX_ProductionOperators_EmployeeNumber
ON ProductionOperators(EmployeeNumber);

-- Consultas por operador y fecha
CREATE INDEX IX_Production_Operator_Time
ON Production(OperatorId, TimeScane);

INSERT INTO ProductionOperators 
(EmployeeNumber, NameOperator, LastnameOperator, AreaId, Operation, Goal, Active)
VALUES
(211, 'ZURI SADAY', 'FLORES SANCHEZ', 1, 'COSTURA', 40, 1),
(1445, 'LESLY GUADALUPE', 'ROJAS VALVERDE', 1, 'COSTURA', 40, 1),
(2430, 'YULISSA', 'ORDOÑEZ ORDOÑEZ', 1, 'COSTURA', 40, 1),
(2660, 'YURI LILIANA', 'LOZOYA MEDINA', 1, 'COSTURA', 40, 1),
(2690, 'ESMERALDA GUADALUPE', 'BRIONES GARCIA', 1, 'COSTURA', 40, 1),
(3155, 'YAJAIRA DE LOS ANGELES', 'ZARATE IGLESIAS', 1, 'COSTURA', 40, 1),
(2338, 'MARIA DEL ROSARIO', 'PEREZ GARCIA', 1, 'COSTURA', 40, 1),
(2407, 'MARIA GUADALUPE', 'SALDAÑA GONZALEZ', 1, 'COSTURA', 40, 1),
(2537, 'EVELYN AMELIA', 'RIVERA MARTINEZ', 1, 'COSTURA', 40, 1),
(2622, 'SAN JUANA', 'DOMINGUEZ VALERIO', 1, 'COSTURA', 40, 1),
(2827, 'ESTELA', 'GAMEZ MENDOZA', 1, 'COSTURA', 40, 1),
(3060, 'ESMERALDA', 'TOVAR ANTONIO', 1, 'COSTURA', 40, 1),
(3080, 'NORMA', 'RAMIREZ MORALES', 1, 'COSTURA', 40, 1),
(3186, 'CARLOS MIGUEL', 'LUNA MAR', 1, 'COSTURA', 40, 1),
(826, 'FRIDA ASTRID', 'MARTINEZ NORBERTO', 1, 'COSTURA', 40, 1),
(1369, 'MIRIAM LIZBETH', 'DIAZ CRISTALES', 1, 'COSTURA', 40, 1),
(1782, 'MARTHA PATRICIA', 'PADILLA MARTINEZ', 1, 'COSTURA', 40, 1),
(1864, 'MARIA GUADALUPE', 'ALVARADO RICO', 1, 'COSTURA', 40, 1),
(2092, 'ALICIA', 'RODRIGUEZ ESCOBEDO', 1, 'COSTURA', 40, 1),
(2911, 'PAOLA JACKELIN', 'DEL ANGEL PEREZ', 1, 'COSTURA', 40, 1),
(3090, 'BRENDA LIZ', 'CRUZ ROJAS', 1, 'COSTURA', 40, 1),
(3169, 'JANETH', 'FELIPE CRUZ', 1, 'COSTURA', 40, 1),
(3172, 'ARELY', 'MARTINEZ GONZALEZ', 1, 'COSTURA', 40, 1),
(2229, 'ADRIANA', 'GONZALEZ ORDOÑEZ', 1, 'COSTURA', 40, 1);


INSERT INTO [KPIS].[dbo].[ProductionOperators]
([EmployeeNumber],[NameOperator],[LastnameOperator],[AreaId],[Operation],[Goal],[Active])
VALUES
(406,  'FILOMENO', 'MORENO SANCHEZ', 1, 'ALINEADO', 40, 1),
(1158, 'JULIO CESAR', 'ACUÑA TORRES', 1, 'ALINEADO', 40, 1),
(2471, 'JUAN ALBERTO', 'FAJARDO FLORES', 1, 'ALINEADO', 40, 1),
(2565, 'HUGO ALBERTO', 'TREJO TREVIÑO', 1, 'ALINEADO', 40, 1),
(2662, 'RUPERTO', 'ACUÑA MENDEZ', 1, 'ALINEADO', 40, 1),
(2807, 'IVAN DE JESUS', 'ACUÑA GUERRERO', 1, 'ALINEADO', 40, 1),
(2917, 'ALEJANDRO', 'HERNANDEZ ANTONIO', 1, 'ALINEADO', 40, 1),
(2962, 'SERGIO ARMANDO', 'RIVERA JUAREZ', 1, 'ALINEADO', 40, 1),
(2968, 'JOSE ALEXIS', 'MIRELES GARCIA', 1, 'ALINEADOR', 40, 1),
(3074, 'MARTIN', 'HERNANDEZ SALAZAR', 1, 'ALINEADO', 40, 1),
(3095, 'JORGE ALFONSO', 'CARRILLO RIVERA', 1, 'ALINEADO', 40, 1),
(3114, 'PEDRO ANTONIO', 'CANTU MALDONADO', 1, 'ALINEADO', 40, 1);


INSERT INTO [KPIS].[dbo].[ProductionOperators]
([EmployeeNumber],[NameOperator],[LastnameOperator],[AreaId],[Operation],[Goal],[Active])
VALUES
(292,  'MAYRA GUADALUPE', 'SANDOVAL RIOS', 1, 'PEGADO', 40, 1),
(1173, 'RAYMUNDO', 'GUTIERREZ ESCOBAR', 1, 'PEGADO', 40, 1),
(1404, 'NELI', 'HERNANDEZ CRUZ', 1, 'PEGADO', 40, 1),
(2365, 'MAGDALENA', 'NAVARRO ANTONIO', 1, 'PEGADO', 40, 1),
(2948, 'JEZMIN KARINA', 'GOMEZ JIMENEZ', 1, 'PEGADO', 40, 1),
(2980, 'GRISEL GUADALUPE', 'HERNANDEZ HERNANDEZ', 1, 'PEGADO', 40, 1),
(3129, 'SILVIA', 'CONTRERAS GARCIA', 1, 'PEGADO', 40, 1),
(648,  'MA DEL SOCORRO', 'RUBIO CRUZ', 1, 'PEGADO', 40, 1),
(2242, 'ROCIO BERENICE', 'SALDIERNA RUIZ', 1, 'PEGADO', 40, 1),
(2625, 'ESMERALDA', 'GONZALEZ GUERRA', 1, 'PEGADO', 40, 1),
(2667, 'ANA JACQUELINE', 'CHAVERO GARCIA', 1, 'PEGADO', 40, 1),
(2752, 'CYNTHIA PATRICIA', 'LOPEZ MIRELES', 1, 'PEGADO', 40, 1),
(2810, 'LUCIA ANGELICA', 'RODRIGUEZ GUERRA', 1, 'PEGADO', 40, 1),
(2870, 'MIGDALIA ANAHI', 'RODRIGUEZ GRACIA', 1, 'PEGADO', 40, 1),
(2903, 'JUAN CARLOS', 'BLANCO PEREZ', 1, 'PEGADO', 40, 1);


